### ISSUE TITLE
Broken craft recipes

### ISSUE THREAD

**Issue by axcore** [AnnalysaTheMinetester/cheese#1]
Some craft recipes are using an unknown item.

![craft](https://user-images.githubusercontent.com/37951926/172777587-1194356d-1a3b-476d-abd9-b719e97613e1.png)

Minetest 5.5.1, using a new world with only minetest-game, unified_inventory and cheese enabled.

**Comment by AnnalysaTheMinetester** [comment]
Hello! Thank you for checking out my mod!
Sorry for the inconvenience. I feel like i have to explain two things.
1. This mod obviously requires some mobs mod, because the milk bucket is the main ingredient of the mod. But i cant set hard dependencies, because you can choose to have only mobs, only petz, only animalia, or any combination of them, therefor the cheeses and dairy get registered, but it could very well be that none of them is installed, just like in your case, resulting in no way to get those items. So what you are seeing is me forgetting to move the unified inventory code inside a check just for this case. Sorry.
2. I deliberately choose to let the cheese and some dairy to get registered, even if there are no means to get them, if there is no milk bucket. To let people check out on them, and maybe later on decide to install a cow-including mod. Or maybe a server who has a shop selling them, so people can still enjoy them even if they cant acquire them on their own. I dont know how people will use my mod.
Still you made me think of ways to better write my code to let people have at least some way to acquire a certain set of items with the bare minimum of mods installed. Thank you!
I will adjust the code soon.
Have a nice day!

**Comment by AnnalysaTheMinetester** [comment]
I have gitted a new version, with more default options, better checks, fixes and a new item Banana Split.
You shouldnt see any more unknown items in unified inventory. Enojy!
