### ISSUE TITLE
Wrong return item with Hunger_NG

### ISSUE THREAD

**Issue by ghost** [AnnalysaTheMinetester/cheese#14]
@AnnalysaTheMinetester 

Hi, nice texture, but in combination with Hunger_NG there is a little oversight.

In the items.lua line 457, it's still returns = "default:copper_ingot", instead of the new cheese:fondue_pot.

While without Hunger_NG it give the Fondue Pot back.

That's all.

**Comment by AnnalysaTheMinetester** [comment]
Sorry for the inconvenience!
I hope that you like the current state of my cheese mod!
Bye!

**Comment by BlockAndPixelAge** [comment]
Don't worry about it, it's was not a inconvenience.

I could actually tell you what a real inconvenience is. A mod that has an Issue for 2 years, that only got fixed 3rd April this year, sadly it's on the forks main branch, with two more files, that should not be implemented, now needing someone to do the pull request with only the specific fixed files, while even knowing how to do commit author ---amend.

And it's still not implemented.

Sorry for the little rant, but the Issue here was not a inconvenience at all.

It's a really nice mod.

Otherwise thank you for fixing the Issue. ;)
